### ISSUE TITLE
Error in training tired-imagenet

### ISSUE THREAD

**Issue by leoshine** [fiveai/making-better-mistakes#2]
Traceback (most recent call last):
  File "scripts/start_training.py", line 349, in <module>
    main_worker(gpus_per_node, opts)
  File "scripts/start_training.py", line 173, in main_worker
    train_loader, model, loss_function, distances, soft_labels, classes, opts, epoch, steps, optimizer, is_inference=False, corrector=corrector,
  File "making-better-mistakes/better_mistakes/model/run_xent.py", line 116, in run
    topK_hdist[i, j] = distances[(classes[class_idx_predicted], classes[class_idx_ground_truth])]
IndexError: list index out of range

In the data_paths.yml:
I specify:
%----------------------------------------------
tiered-imagenet-224:  /path/to/ImageNet/
%----------------------------------------------
 
It looks like tired-imagenet dataset needs other ways to prepare?

**Comment by leoshine** [comment]
Just figured out that I need to construct the tieredImagenet-H dataset myself.
For those who are not aware of this:
     The train/val/test splits (which are subsets of train/val sets of the original ImageNet ilsvcr12) are specified here:  dataset_splits/splits_tiered.zip
